config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  
  resources :users, only: [:new, :create, :show]

  resources :topics, only: :show do
    resources :questions
    resources :posts
  end

  resources :questions do 
    resources :comments, except: [:show, :delete]
  end 

  resources :posts do 
    resources :comments, except: [:show, :delete]
  end 


  post "topics/:topic_id/questions/:id/solved", to: "questions#solved", as: 'solved'
  match "users/most-frequent-poster", to: "users#mf_poster", as: "most_posts", via: [:get, :post]

  match '/auth/:provider/callback', to: 'sessions#github', via: [:get, :post] 
  get 'auth/failure', to:  'users#new'

  
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
    belongs_to :question
    validates :content, presence: true  

    validates :content, length: {maximum: 200}

    def topic
        if post 
            post.topic
        else 
            question.topic
        end 
    end
    




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_comment, only: [:show, :edit, :update]

    def index
        if find_post
            @comments = @post.comments
        elsif find_question
            @comments = @question.comments
        else render :new
        end 
    end 

    
    def new 
        @comment = Comment.new
        if find_post
        elsif find_question
        else render :new
        end 
    end 

    def create 
        @comment = Comment.new(comment_params)
        if @comment.save && @comment.post 
            redirect_to topic_post_path(@comment.topic, @comment.post)
        elsif @comment.save && @comment.question
            redirect_to topic_question_path(@comment.topic, @comment.question)
        else 
            question_or_post
            render :new 
        end  
    end 


    def edit
        if @comment.user == current_user 
            if find_post
            elsif find_question
            end 
        else redirect_to topic_path(@comment.topic) 
        end 
    end
    
    def update
        if @comment && @comment.post
            @comment.update(comment_params)
            redirect_to topic_post_path(@comment.topic, @comment.post)
        elsif @comment && @comment.question
            @comment.update(comment_params) 
            redirect_to topic_question_path(@comment.topic, @comment.question)
        else question_or_post
            redirect_to :edit
        end  
    end 
    
    private 

    def find_comment
        @comment = Comment.find_by(id: params[:id])
    end 

    def comment_params
        params.require(:comment).permit(:post_id, :question_id, :user_id, :answer, :content)
    end 
end

app/helpers/comments_helper.rb
module CommentsHelper



end

app/views/comments/_display.html.erb
<h4>
<% if @post %> 
    <% if comment.user == current_user %>
    <%= link_to "You said #{comment.content}", edit_post_comment_path(@post,comment) %> <br>
    <% else %> 
    <%= "#{comment.user.name}: #{comment.content}"  %> <br>
    <% end %> 
<% else @question %>
    <% if comment.user == current_user && comment.answer %>
    <%= link_to "You answered #{comment.content}", edit_question_comment_path(@question,comment), class: "answers" %> 
    <% elsif comment.user == current_user %>
    <%= link_to "You said #{comment.content}", edit_question_comment_path(@question,comment) %>
    <% else %> 
        <% if comment.answer %>
            <div class="answers"> <%= "#{comment.user.name} answered #{comment.content}"%> </div>
        <% else %>
            <%= "#{comment.user.name}: #{comment.content}"  %> <br>
        <% end %>
    <% end %>
<% end %>
</h4>

app/views/comments/_form.html.erb
<% if @post %>
<%= form_for [@post, @comment] do |f| %>
<%= f.hidden_field :post_id, value: @post.id %>
<%= f.hidden_field :user_id, value: current_user.id %>
<span class="largeFont" ><%= f.label :content, "Comment" %>  </span> <br>
<%= f.text_area :content, value: @comment.content %> <br>  <br>
<%= f.submit :class => 'button3' %>  
<% end %> 
<% else @question %>
<%= form_for [@question, @comment] do |f| %>
<%= f.hidden_field :question_id, value: @question.id %>
<%= f.hidden_field :user_id, value: current_user.id %>
<span class="largeFont" ><%= f.label :answer, "Check box if this is an attempted answer!" %> </span>  <br>
<%= f.check_box :answer, {class:"form-check-input", type:"checkbox"}, true, false  %> <br> <br>
<span class="largeFont" ><%= f.label :content, "Comment/Answer" %>  </span> <br>
<%= f.text_area :content, value: @comment.content %> <br>  <br>
<%= f.submit :class => 'button3' %>  
<% end %>
<% end %>

app/views/comments/edit.html.erb
<h3> <%= comment_title %> </h3>
<h3> Edit Comment  </h3>
<h4 class="intro"> Make sure your comment is related and makes sense. </h4>

<%= render "form" %>

app/views/comments/index.html.erb
 <h3> <%= comment_title %> </h3>

<h4> Comments </h4>

<%= render :partial => "display", :collection => @comments, :as => :comment %>

app/views/comments/new.html.erb
<h3> <%= comment_title %> </h3>

<h3> What's your comment? </h3>

<%= render "form" %>