config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  
  resources :users, only: [:new, :create, :show]

  resources :topics, only: :show do
    resources :questions
    resources :posts
  end

  resources :questions do 
    resources :comments, except: [:show, :delete]
  end 

  resources :posts do 
    resources :comments, except: [:show, :delete]
  end 


  post "topics/:topic_id/questions/:id/solved", to: "questions#solved", as: 'solved'
  match "users/most-frequent-poster", to: "users#mf_poster", as: "most_posts", via: [:get, :post]

  match '/auth/:provider/callback', to: 'sessions#github', via: [:get, :post] 
  get 'auth/failure', to:  'users#new'

  
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts 
    has_many :comments, through: :posts
    has_many :questions  
    has_many :answers, through: :questions
    has_many :users, through: :posts

   
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

    def show 
        @topic = Topic.find_by(id: params[:id])
    end 


end

app/helpers/topics_helper.rb
module TopicsHelper

    def topic_people
        Topic.all.find_by(id: 1)
    end 

    def topic_places
        Topic.all.find_by(id: 2)
    end 

    def topic_events
        Topic.all.find_by(id: 3)
    end 
end

app/views/topics/show.html.erb
<h1> <%= @topic.name %> </h1>

<div class="container main-info">
<h3> <em> <u> Knowledge for Sharing </u> </em> </h3> <br>
 <%= render :partial => "posts/linked-display", :collection => @topic.posts, :as => :post %>
<br><br>
<%= button_to "Drop Some Knowledge", new_topic_post_path(@topic), :method => :get, class: "button3"  %> 
</div>

<div class="container main-info">
<h3> <em> <u>  Questions and Answers </u> </em> </h3> <br>
<%= render :partial => "questions/linked-display", :collection => @topic.questions, :as => :question %>
<br><br>
<%= button_to "Post Question(s)", new_topic_question_path(@topic), :method => :get, class: "button3" %> <br><br>
 </div>
 