config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  
  resources :users, only: [:new, :create, :show]

  resources :topics, only: :show do
    resources :questions
    resources :posts
  end

  resources :questions do 
    resources :comments, except: [:show, :delete]
  end 

  resources :posts do 
    resources :comments, except: [:show, :delete]
  end 


  post "topics/:topic_id/questions/:id/solved", to: "questions#solved", as: 'solved'
  match "users/most-frequent-poster", to: "users#mf_poster", as: "most_posts", via: [:get, :post]

  match '/auth/:provider/callback', to: 'sessions#github', via: [:get, :post] 
  get 'auth/failure', to:  'users#new'

  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end 
end

app/views/welcome/home.html.erb
<h1> Welcome<%= ", #{current_user.name}" if current_user %>! </h1>

<br><h4 class="intro"> Black History Social is website to learn and inform with other people about the history of African and African-Americans across the known universe. 
The content on the website is user generated and can be public knowledge or local knowledge about people, places, and events that may not be commonly known. 
You can think of it as a user generated encyclopedia built for users by users. </h4>

<br> <h4 class="qoute"> "What you're calling African history, Black history, are the missing pages of World history"  </h4>
<h4 class="qoute"> - Arthur Schomburg </h4>

<% if current_user  %>

<br><h4 class="intro"> You can click <em> Knowledge is Power </em> to return here at any point. The buttons below will help you get started and familar with the process. You can either make a post about something you learned or know
in African or African-American history, with the title being the person, place, or event your post is about, or you can post a question in any of those 
categories to other people and users of <strong> Black History Social</strong>. Everyone is able to comment on other posts or questions, and you can also attempt 
to answer other user's questions but only they can determine if the question has been answered. </h4> <br>

<h4> You currently have <%= current_user.posts.count %> posts, <%=  current_user.questions.count %> questions, and <%= current_user.comments_to_posts.count + current_user.comments_to_questions.count %> comment(s)/answer(s). </h4> 
<h4> <u> <%= link_to "View Profile", user_path(current_user) %> </u></h4> 

<%= button_to "Most Frequent Poster", most_posts_path, :method => :post, class: "button3"  %> 

<br><h4> Current topics below: </h4> 

<div class="container topic-info">
<%= button_to "People", topic_path(topic_people), :method => :get, class: "button3"  %> 
</div>


<div class="container topic-info">
<%= button_to "Places", topic_path(topic_places), :method => :get, class: "button3"  %> 
</div>

<div class="container topic-info">
<%= button_to "Events", topic_path(topic_events), :method => :get, class: "button3"  %> 
</div>

<% end %> 

<br><br>