config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  
  resources :users, only: [:new, :create, :show]

  resources :topics, only: :show do
    resources :questions
    resources :posts
  end

  resources :questions do 
    resources :comments, except: [:show, :delete]
  end 

  resources :posts do 
    resources :comments, except: [:show, :delete]
  end 


  post "topics/:topic_id/questions/:id/solved", to: "questions#solved", as: 'solved'
  match "users/most-frequent-poster", to: "users#mf_poster", as: "most_posts", via: [:get, :post]

  match '/auth/:provider/callback', to: 'sessions#github', via: [:get, :post] 
  get 'auth/failure', to:  'users#new'

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlackHistroySocial</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
      <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
      <script src="https://apis.google.com/js/platform.js?onload=init" async defer></script>
  </head>
  <body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag("basquiat_crown_KiP.png", :alt => "Knowledge Crown") %>
      <a class="navbar-brand" href="/">Knowledge is Power</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
      <% if current_user %>
        <li><%= link_to "People", topic_path(topic_people)%></li>
        <li><%= link_to "Places", topic_path(topic_places) %></li>
        <li><%= link_to "Events", topic_path(topic_events) %></li>
        <% else %>
        <li class="active"><%= link_to "Home", root_path %></li>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Sign In", login_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
 </nav>

 <div class="container">
  

  <div class="text-center">
    <h1>Black History Social</h1>


    

    <% if flash[:messages] %>
   <% flash[:messages].each do |message| %>
      <div class="messages"><%= message %></div> <br>
   <% end %>
 <% end %>

    <%= yield %>
    
    
  </div> <!-- /.text-center -->
 </div> <!-- /.container -->
  <br><br> <center> <% if current_user %>
    <%= link_to "Log Out", logout_path, action: :delete, :method => :post, class: "logout", class: "button3" %>
    <% end %>
    </center>
    

  </body>
    
  <footer class="branding">
        <small>&copy; 2021 <strong>Black Histroy Social </strong></small>
       
      </footer>

  
</html>